/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dividebyxero_dbxcapture_jni_DBXCNativeInterface */

#ifndef _Included_com_dividebyxero_dbxcapture_jni_DBXCNativeInterface
#define _Included_com_dividebyxero_dbxcapture_jni_DBXCNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_dividebyxero_dbxcapture_jni_DBXCNativeInterface
     * Method:    debugDumpBuffer
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_com_dividebyxero_dbxcapture_jni_DBXCNativeInterface_debugDumpBuffer
    (JNIEnv *, jclass);

    /*
     * Class:     com_dividebyxero_dbxcapture_jni_DBXCNativeInterface
     * Method:    waitForScreenshotActionAndReturnPath
     * Signature: (Ljava/lang/String;I)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_dividebyxero_dbxcapture_jni_DBXCNativeInterface_waitForScreenshotActionAndReturnPath
    (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
